import test from 'node:test';
import assert from 'node:assert/strict';

// NOTE: tests run against dist output (generated by npm run build).
import {
  normalizeFeishuText,
  extractFromPostJson,
  buildInboundFromFeishuMessage,
} from '../dist/src/inbound-media.js';

// ─── normalizeFeishuText ──────────────────────────────────────

test('normalizeFeishuText: strips HTML tags and decodes entities', () => {
  const input = '<p>Hello &amp; <b>world</b></p>';
  const result = normalizeFeishuText(input);
  assert.equal(result, 'Hello & world');
});

test('normalizeFeishuText: converts <br> and </p><p> to newlines', () => {
  const input = 'line1<br/>line2</p><p>line3';
  const result = normalizeFeishuText(input);
  assert.equal(result, 'line1\nline2\nline3');
});

test('normalizeFeishuText: fixes list quirk — marker split across lines', () => {
  const input = '-\nitem1\n-\nitem2';
  const result = normalizeFeishuText(input);
  assert.equal(result, '- item1\n- item2');
});

test('normalizeFeishuText: fixes numbered list quirk', () => {
  const input = '1.\nfirst\n2.\nsecond';
  const result = normalizeFeishuText(input);
  assert.equal(result, '1. first\n2. second');
});

test('normalizeFeishuText: collapses excessive newlines', () => {
  const input = 'a\n\n\n\n\nb';
  const result = normalizeFeishuText(input);
  assert.equal(result, 'a\n\nb');
});

// ─── extractFromPostJson ──────────────────────────────────────

test('extractFromPostJson: extracts text from simple post', () => {
  const post = {
    title: '标题',
    content: [
      [
        { tag: 'text', text: 'Hello ' },
        { tag: 'text', text: 'world' },
      ],
    ],
  };
  const { text, imageKeys } = extractFromPostJson(post);
  assert.ok(text.includes('标题'));
  assert.ok(text.includes('Hello world'));
  assert.equal(imageKeys.length, 0);
});

test('extractFromPostJson: extracts image keys from post', () => {
  const post = {
    content: [
      [
        { tag: 'text', text: 'see this:' },
        { tag: 'img', image_key: 'img_key_abc' },
      ],
      [
        { tag: 'img', image_key: 'img_key_def' },
      ],
    ],
  };
  const { text, imageKeys } = extractFromPostJson(post);
  assert.ok(text.includes('see this:'));
  assert.deepEqual(imageKeys, ['img_key_abc', 'img_key_def']);
});

test('extractFromPostJson: deduplicates image keys', () => {
  const post = {
    content: [
      [{ tag: 'img', image_key: 'img_same' }],
      [{ tag: 'img', image_key: 'img_same' }],
    ],
  };
  const { imageKeys } = extractFromPostJson(post);
  assert.equal(imageKeys.length, 1);
  assert.equal(imageKeys[0], 'img_same');
});

test('extractFromPostJson: handles code_block', () => {
  const post = {
    content: [
      [{ tag: 'code_block', language: 'python', text: 'print("hi")' }],
    ],
  };
  const { text } = extractFromPostJson(post);
  assert.ok(text.includes('python'));
  assert.ok(text.includes('print("hi")'));
});

test('extractFromPostJson: handles links and mentions', () => {
  const post = {
    content: [
      [
        { tag: 'at', user_name: 'Alice' },
        { tag: 'text', text: ' check ' },
        { tag: 'a', text: 'this link', href: 'https://example.com' },
      ],
    ],
  };
  const { text } = extractFromPostJson(post);
  assert.ok(text.includes('@Alice'));
  assert.ok(text.includes('this link'));
});

// ─── buildInboundFromFeishuMessage (text) ─────────────────────

test('buildInbound: text message returns normalized text', async () => {
  const fakeClient = {};
  const message = {
    message_id: 'om_test',
    message_type: 'text',
    content: JSON.stringify({ text: 'Hello <b>bot</b>' }),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  assert.equal(result.text, 'Hello bot');
  assert.equal(result.attachments.length, 0);
});

// ─── buildInboundFromFeishuMessage (image) ────────────────────

test('buildInbound: image message downloads and attaches image', async () => {
  const fakeClient = {
    im: {
      messageResource: {
        get: async () => Buffer.from('fake-png-data'),
      },
    },
  };
  const message = {
    message_id: 'om_img',
    message_type: 'image',
    content: JSON.stringify({ image_key: 'img_key_test' }),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  assert.equal(result.text, '[图片]');
  assert.equal(result.attachments.length, 1);
  assert.equal(result.attachments[0].type, 'image');
  assert.ok(result.attachments[0].content.startsWith('data:image/png;base64,'));
});

// ─── buildInboundFromFeishuMessage (post with images) ─────────

test('buildInbound: post message extracts text and downloads embedded images', async () => {
  const fakeClient = {
    im: {
      messageResource: {
        get: async () => Buffer.from('fake-thumb'),
      },
    },
  };
  const postContent = {
    title: 'Test Post',
    content: [
      [
        { tag: 'text', text: 'Look at this:' },
        { tag: 'img', image_key: 'img_post_1' },
      ],
    ],
  };
  const message = {
    message_id: 'om_post',
    message_type: 'post',
    content: JSON.stringify(postContent),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  assert.ok(result.text.includes('Test Post'));
  assert.ok(result.text.includes('Look at this:'));
  assert.equal(result.attachments.length, 1);
  assert.equal(result.attachments[0].type, 'image');
});

// ─── buildInboundFromFeishuMessage (file) ─────────────────────

test('buildInbound: file message downloads to temp path', async () => {
  const fakeClient = {
    im: {
      messageResource: {
        get: async () => Buffer.from('file-content-here'),
      },
    },
  };
  const message = {
    message_id: 'om_file',
    message_type: 'file',
    content: JSON.stringify({ file_key: 'fk_123', file_name: 'report.pdf' }),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  assert.ok(result.text.includes('[文件] report.pdf'));
  assert.ok(result.text.includes('file://'));
});

// ─── buildInboundFromFeishuMessage (audio) ────────────────────

test('buildInbound: audio message downloads to temp path', async () => {
  const fakeClient = {
    im: {
      messageResource: {
        get: async () => Buffer.from('audio-data'),
      },
    },
  };
  const message = {
    message_id: 'om_audio',
    message_type: 'audio',
    content: JSON.stringify({ file_key: 'fk_audio', file_name: 'voice.opus' }),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  assert.ok(result.text.includes('[语音] voice.opus'));
  assert.ok(result.text.includes('file://'));
});

// ─── buildInboundFromFeishuMessage (media/video) ──────────────

test('buildInbound: media message downloads video and thumbnail', async () => {
  const fakeClient = {
    im: {
      messageResource: {
        get: async () => Buffer.from('video-or-thumb-data'),
      },
    },
  };
  const message = {
    message_id: 'om_video',
    message_type: 'media',
    content: JSON.stringify({
      file_key: 'fk_vid',
      file_name: 'demo.mp4',
      duration: 5000,
      image_key: 'thumb_key',
    }),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  assert.ok(result.text.includes('[视频] demo.mp4'));
  assert.ok(result.text.includes('5000ms'));
  assert.ok(result.text.includes('file://'));
  // Should have a thumbnail attachment
  assert.equal(result.attachments.length, 1);
  assert.equal(result.attachments[0].type, 'image');
});

// ─── buildInboundFromFeishuMessage (fallback) ─────────────────

test('buildInbound: unknown content falls back gracefully', async () => {
  const fakeClient = {};
  const message = {
    message_id: 'om_unk',
    message_type: 'text',
    content: JSON.stringify({ text: '' }),
  };
  const result = await buildInboundFromFeishuMessage(fakeClient, message);
  // Should use fallback since text is empty and no attachments
  assert.ok(result.text.includes('Feishu'));
});

// ─── buildInboundFromFeishuMessage (image download failure) ───

test('buildInbound: image download failure falls back to placeholder', async () => {
  const errors = [];
  const fakeClient = {
    im: {
      messageResource: {
        get: async () => { throw new Error('network error'); },
      },
    },
  };
  const message = {
    message_id: 'om_fail',
    message_type: 'image',
    content: JSON.stringify({ image_key: 'img_broken' }),
  };
  const result = await buildInboundFromFeishuMessage(
    fakeClient,
    message,
    {},
    { error: (msg) => errors.push(msg) },
  );
  assert.equal(result.text, '[图片]');
  assert.equal(result.attachments.length, 0);
  assert.ok(errors.length > 0);
  assert.ok(errors[0].includes('network error'));
});
